### ISSUE TITLE
Missing XML Namespace?

### ISSUE THREAD

**Issue by ZKjellberg** [spring-guides/gs-validating-form-input#19]
Shouldn't **templates/form.html** have the XML namespace defined to properly use **th**?

[Presently, line 0 has just the html tag](https://github.com/spring-guides/gs-validating-form-input/blob/master/complete/src/main/resources/templates/form.html)

```<html xmlns:th="http://www.thymeleaf.org">```

**Comment by gregturn** [comment]
Sounds like a great idea. Have time for a PR?

**Comment by ZKjellberg** [comment]
PR #20 implements the fix.
