### ISSUE TITLE
Upgrade Spring Boot version

### ISSUE THREAD

**Issue by Buzzardo** [spring-guides/gs-validating-form-input#40]
An easy (at least relatively speaking) place for beginners to jump in is to upgrade to the latest patch release of Spring Boot. I'm opening this issue to encourage people to dive in.

The following files need to have the Spring Boot version updated:

initial/build.gradle
initial/pom.xml
complete/build.gradle
complete/pom.xml

**Comment by robertmcnees** [comment]
Closing in favor of managing this at a higher level.
